# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/*
      - '*.json'
      - package-lock.json
  pull_request:
    paths:
      - '!*.MD'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: test/node 12.x/ubuntu-latest
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: coverage
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - uses: paambaati/codeclimate-action@v2.5.4
        env:
          CC_TEST_REPORTER_ID: 44b4d2618b646679609a8814fb004870c6f3a0f07901fbe3880486869923e75c
        with:
          coverageCommand: npm test -- --coverage
